In [2]:
from pandas import DataFrame
from selenium import webdriver 


import pandas as pd

In [3]:
df = pd.read_csv("title.basics.tsv", sep="\t",nrows=1000)
df_filter = df[df['titleType'] == 'movie']
df_filter_reset_index = df_filter.reset_index()

In [4]:
df_filter_reset_index

,index,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,8,tt0000009,movie,Miss Jerry,Miss Jerry,0,1894,\N,45,Romance
1,145,tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,0,1897,\N,20,"Documentary,News,Sport"
2,332,tt0000335,movie,Soldiers of the Cross,Soldiers of the Cross,0,1900,\N,\N,"Biography,Drama"
3,499,tt0000502,movie,Bohemios,Bohemios,0,1905,\N,100,\N
4,571,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906,\N,70,"Biography,Crime,Drama"
5,611,tt0000615,movie,Robbery Under Arms,Robbery Under Arms,0,1907,\N,\N,Drama
6,626,tt0000630,movie,Hamlet,Amleto,0,1908,\N,\N,Drama
7,669,tt0000675,movie,Don Quijote,Don Quijote,0,1908,\N,\N,Drama
8,670,tt0000676,movie,Don Álvaro o la fuerza del sino,Don Álvaro o la fuerza del sino,0,1908,\N,\N,Drama
9,673,tt0000679,movie,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,0,1908,\N,120,"Adventure,Fantasy"
10,730,tt0000739,movie,El pastorcito de Torrente,El pastorcito de Torrente,0,1908,\N,\N,Drama
11,784,tt0000793,movie,Andreas Hofer,Andreas Hofer,0,1909,\N,\N,Drama
12,803,tt0000812,movie,El blocao Velarde,El blocao Velarde,0,1909,\N,\N,\N
13,805,tt0000814,movie,La bocana de Mar Chica,La bocana de Mar Chica,0,1909,\N,\N,\N
14,829,tt0000838,movie,A Cultura do Cacau,A Cultura do Cacau,0,1909,\N,\N,\N
15,833,tt0000842,movie,De Garraf a Barcelona,De Garraf a Barcelona,0,1909,\N,\N,\N
16,837,tt0000846,movie,Un día en Xochimilco,Un día en Xochimilco,0,1909,\N,\N,\N
17,841,tt0000850,movie,Los dos hermanos,Los dos hermanos,0,1909,\N,\N,\N
18,850,tt0000859,movie,Fabricación del corcho en Sant Feliu de Guixols,Fabricación del corcho en Sant Feliu de Guixols,0,1909,\N,\N,\N
19,853,tt0000862,movie,Faldgruben,Faldgruben,0,1909,\N,\N,\N
20,858,tt0000867,movie,Fiesta de toros,Fiesta de toros,0,1909,\N,\N,\N
21,859,tt0000868,movie,Fiestas de Santa Lucía - Belenes,Fiestas de Santa Lucía - Belenes,0,1909,\N,\N,\N
22,860,tt0000869,movie,Fiestas en La Garriga,Fiestas en La Garriga,0,1909,\N,\N,\N
23,870,tt0000879,movie,Gira política de Madero y Pino Suárez,Gira política de Madero y Pino Suárez,0,1909,\N,\N,\N
24,877,tt0000886,movie,"Hamlet, Prince of Denmark",Hamlet,0,1910,\N,\N,Drama
25,931,tt0000941,movie,Locura de amor,Locura de amor,0,1909,\N,\N,Drama
26,937,tt0000947,movie,Lægens offer,Lægens offer,0,1909,\N,\N,\N
27,949,tt0000959,movie,Melilla y el Gurugu,Melilla y el Gurugu,0,1909,\N,\N,\N
28,973,tt0000984,movie,Niños en la alameda,Niños en la alameda,0,1909,\N,\N,\N
29,981,tt0000992,movie,De onde Veje,De onde Veje,0,1909,\N,\N,\N
30,996,tt0001007,movie,La primera y segunda casetas,La primera y segunda casetas,0,1909,\N,\N,\N
31,999,tt0001010,movie,Protección de un convoy de víveres en el puent...,Protección de un convoy de víveres en el puent...,0,1909,\N,\N,\N

In [5]:
ids_film = df_filter_reset_index['tconst'].tolist()
len(ids_film)

32

In [11]:
driver = webdriver.Chrome(executable_path='local/chromedriver')
correct_films = 0

#test_list = ['tt7286456',ids_film[538827],'tt0187393']

for num,film in enumerate(ids_film):
    
    print("Imagen número:",num,", ID:", film)

    url = 'https://www.imdb.com/title/'+film+'/?ref_=fn_al_tt_1' 
    #url = 'https://pro.imdb.com/title/'+film
    driver.get(url)
    
    # Busca los elementos que tienen en el contenido un determinado texto, budget y cumulative...
    #description = driver.find_element_by_class_name('title_wrapper')
    img = driver.find_element_by_class_name('poster').find_element_by_class_name()
    src = img.get_attribute('src')
    tag_name = "film"
    os.system("wget %s --no-check-certificate -O %s.png"%(src,tag_name))
    print(img.text)
driver.close()

Imagen número: 0 , ID: tt0000009

NameError: name 'os' is not defined

In [119]:
df = DataFrame.from_csv("title.ratings.tsv", sep="\t")

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.

In [120]:
df

           averageRating  numVotes
tconst
tt0000001            5.6      1572
tt0000002            6.1       189
tt0000003            6.5      1236
tt0000004            6.2       116
tt0000005            6.1      1973
tt0000006            5.2       107
tt0000007            5.4       624
tt0000008            5.4      1696
tt0000009            5.4        86
tt0000010            6.9      5630
tt0000011            5.2       242
tt0000012            7.4      9556
tt0000013            5.7      1470
tt0000014            7.1      4181
tt0000015            6.1       756
tt0000016            5.9      1110
tt0000017            4.6       222
tt0000018            5.4       456
tt0000019            5.5        17
tt0000020            5.0       253
tt0000022            5.1       821
tt0000023            5.6      1048
tt0000024            5.0        32
tt0000025            4.4        25
tt0000026            5.7      1245
tt0000027            5.5       866
tt0000028            5.1       791
tt0000029            5.9      2677
tt0000030            5.3       654
tt0000031            5.5       770
...                  ...       ...
tt9915754            8.6         5
tt9915780            8.4         8
tt9915790            7.1         8
tt9915820            8.1        22
tt9915822            8.9         7
tt9915824            7.9        21
tt9915832            8.4        22
tt9915864            7.5        17
tt9915898            9.1       111
tt9915906            7.7        69
tt9915910            9.1        92
tt9915912            7.3        64
tt9915928            7.6        37
tt9916114            8.7        20
tt9916160            6.6        33
tt9916192            7.4         9
tt9916200            8.5       137
tt9916204            8.2       163
tt9916206            2.5        11
tt9916316            8.4         5
tt9916348            8.9        14
tt9916380            9.2       100
tt9916420            6.4         8
tt9916428            3.4        10
tt9916544            7.3        11
tt9916576            6.0         8
tt9916578            8.8        14
tt9916720            5.3        44
tt9916766            6.7        11
tt9916778            6.9        16

[1013006 rows x 2 columns]